name: Deploy new version

# Only deploy when a new tag is pushed or manually (workflow_dispatch)
on:
    workflow_dispatch:
    push:
        tags:
          - "v*.*.*"
          
# Must match the project() name in CMakeLists.txt
env:
    APP_NAME: blink
    
# Allow this workflow to write back to the repository
permissions:
    contents: write
    
# Build binary and send to releases
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        name: Build and deploy
        steps:
        
          - name: Check out this repository
            uses: actions/checkout@v3
            
          - name: Build Docker image
            run: docker build -t lpc55s16-image .
            
          - name: Create Docker container
            run: docker create --name lpc55s16-container lpc55s16-image
            
          - name: Copy out .uf2 file
            run: docker cp lpc55s16-container:/project/build/${APP_NAME}.hex ./${APP_NAME}.hex
            
          - name: Put environment variable into the env context
            run: echo "app_name=$APP_NAME" >> $GITHUB_ENV
            
            # for the push, we need the tag!
          - name: Push to release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            with:
                files: ${{ env.app_name }}.hex
                body_path: CHANGELOG.md

                